config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  
  get 'help'    => 'static_pages#help'
  get 'contact'   => 'static_pages#contact'
  get 'about'   => 'static_pages#about'
  get 'servicios'   => 'static_pages#servicios'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def contact
  end
  
  def about
    
  end
  
  def servicios
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_carousel.html.erb
<!-- Carousel -->
          <script type="text/javascript">
            $(document).ready(function() {
              $('.carousel').carousel({
                interval: 2000,
                pause: 'false'
              })
            });
          </script>
          
          <div class="container" id="carousel">

            <div id="myCarousel" class="carousel slide carousel-fade">
              <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
              </ol>
              <!-- Carousel items -->
              <div class="carousel-inner">
                <div class="active item"><%= image_tag 'DisGrafico.jpg' %> </div> 
                <div class="item"><%= image_tag 'ProdGraf.jpg' %></div>
                <div class="item"><%= image_tag 'DisWeb.jpg' %></div>
              </div>
              <!-- Carousel nav -->
              <!--
              <a class="carousel-control left" href="#myCarousel" data-slide="prev" >&lsaquo;Anterior</a>
              <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;Siguiente</a>
              -->
            </div>
          </div> 

app/views/layouts/_footer.html.erb
<footer class="footer">

<div class="container">
<div class="col-xs-12">
  <small>
    <address>
      <strong>Lumapel</strong><br>
       <%= link_to "Los Alelíes OE4-48 y Gualaquiza",    contact_path %><br>
       Quito - Ecuador<br>
    </address>
  </small>  

    <nav>
        <ul>
            <li>
              <span class="glyphicon glyphicon-phone-alt"></span><a href="tel:+59322293948"> 02 229 3984</a>
            </li><br>
            <li>
              <span class="glyphicon glyphicon-phone"></span><a href="tel:+593988137340"> 09 8813 7340</a>
            </li><br>
            <li>
            <span class="glyphicon glyphicon-envelope"><a href="mailto:lumapel@hotmail.com">lumapel@hotmail.com</a>
            </li><br>
        </ul>
      
    </nav>
    </div> 
  </div> 
</footer>

app/views/layouts/_header.html.erb
<!--
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("logoblanco.png", width:'90', alt:'Lumapel'), root_path, id: "logo" %>
    <nav>

      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "Inicio",   root_path, class: 'header_menu_item'  %></li>
        <li><%= link_to "Servicios",   servicios_path, class: 'header_menu_item'  %></li>
        <li><%= link_to "Equipo",    about_path, class: 'header_menu_item'  %></li>
        <li><%= link_to "Contáctanos",    contact_path, class: 'header_menu_item' %></li>
      </ul>
    </nav>
  </div>
</header>
-->

<nav role="navigation" class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag("logoblanco.png", width:'90', alt:'Lumapel'), root_path, id: "logo" %>
        </div>
 
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Inicio",   root_path, class: 'header_menu_item'  %></li>
                <li><%= link_to "Servicios",   servicios_path, class: 'header_menu_item'  %></li>
                <li><%= link_to "Equipo",    about_path, class: 'header_menu_item'  %></li>
                <li><%= link_to "Contáctanos",    contact_path, class: 'header_menu_item' %></li>
            </ul>
        </div>
</nav>

app/views/layouts/_jumbotron.html.erb
<!-- Jumbotron Principal -->
    <div class="center jumbotron other-color">
    
      <div class="container">
            
        <!-- Columna de presentacion -->
          <div class="col-md-4">
            <h1><%= image_tag("logo.png", width:'155', alt:'Lumapel') %></h1>
          </div> 
          <div class="col-md-8">
            <p>Lumapel es una empresa ubicada en Quito - Ecuador, 
              dedicada a realizar diseño gráfico, diseño Web y producción gráfica. 
              Nuestra prioridad es la productividad de nuestros clientes, 
              por lo que hacemos un trabajo de calidad, rápido y a buen precio.
            </p>
  
            <!-- <%= link_to "Conocer más", about_path, class: "btn btn-lg btn-primary" %> -->
          </div>  
      </div>
    </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Lumapel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!--
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script> -->

  <script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

  <%= render 'layouts/shim' %>
  
</head>
<body>
  
  <%= render 'layouts/header' %>
  

        <%= yield %>

  <%= render 'layouts/footer' %>

</body>

</html>

app/views/static_pages/about.html.erb
<% provide(:title, "Equipo") %>
<div class= "container">
  <h1>Equipo Lumapel</h1>

  <!-- Staff Info -->
  <div class="staff-wrap">
    <div class="row">
      <div class="staff-info">
        <div class ="col-md-4">
          <div class ="container">

            <!-- Foto perfil -->
            <div class ="row">
              <div class ="item"><%= image_tag 'Mario.jpg', size: "250", alt: "Mario Hernández" %></div>
            </div>

            <!-- Links de contacto -->
            <div class ="row">

                <!-- Glyphicon con link -->
                <!--
                <li>
                  <%= link_to "mailto:mariohernandezv@yahoo.com.ar" do %>
                  <span class="glyphicon glyphicon-envelope"></span> mariohernandezv@yahoo.com.ar
                  <% end %>
                </li>
                -->
                <li>
                  <span class="glyphicon glyphicon-envelope"></span><a href="mailto:mariohernandezv@yahoo.com.ar"> mariohernandezv@yahoo.com.ar</a>
                </li>
                <li>
                  <span class="glyphicon glyphicon-phone"></span><a href="tel:+593988137340"> 09 8813 73 40</a>
                </li>

            </div>

          </div>
        </div>
        <div class ="col-md-8">
          <h4>Mario Hernández <span></span></h4>
          <p>Ingeniero en Sistemas, fotógrafo, lector incansable, gusta de la música y del cine. El nacer en Quito-Ecuador siendo hijo de padres chilenos, le permitió aprender de ambas culturas.</p>

          <p>Ha trabajado en diseño gráfico, fotografía e imprenta desde 2001, aplicando sus conocimientos sobre sistemas informáticos en mantenimiento de servidores y creación de páginas web. </p>

          <p>El título de Ingeniero en Sistemas y Ciencias de la Computación lo obtuvo en la Universidad Tecnológica Equinoccial. Empezó su carrera en el mundo de la imprenta  como operador de pre-prensa para un periódico de la ciudad. Se fue capacitando en el diseño gráfico y fotografía, hasta ocupar el cargo de director de arte, para luego encargarse del manejo de las operaciones y la comercialización de la empresa en la que trabajaba antes de emprender Lumapel, idea que vio la luz en abril de 2015.
          </p> 
        </div>
      </div>
    </div>
  </div>

  <div class="staff-wrap">
    <div class="row">
      <div class="staff-info">
        <div class ="col-md-4">
          <div class ="container">
            <div class ="row">
              <div class="item"><%= image_tag 'Cecy.jpg', size: "250", alt: "Cecilia Benítez" %></div>
            </div>


              <div class ="row">
                  <li>
                    <span class="glyphicon glyphicon-envelope"></span><a href="mailto:cecybenitez@hotmail.com"> cecybenitez@hotmail.com</a>
                  </li>
                  <li>
                    <span class="glyphicon glyphicon-phone"></span><a href="tel:+593997090665"> 09 9709 06 65</a>
                  </li>

              </div>
            </div>
        </div>


        <div class ="col-md-8">
          <h4>Cecilia Benítez <span></span></h4>
          <p>Master en Diseño Publicitario, fotógrafa, amante del baile flamenco y los boleros. Nace en la ciudad de Quito dentro de una familia dedicada a la aviación, lo que permitió el despegue de su creatividad e imaginación desde muy pequeña en las paredes de su casa. </p>

          <p>Sus estudios se inician en la Universidad San Francisco de Quito en la carrera de Diseño Multimedia, los que luego complementó con una Maestría en Diseño Publicitario en Savannah College of Art and Design, Estados Unidos. </p>

          <p>Ha trabajado como Directora de Arte en la ciudad de Fort Lauderdale, donde cumplió con el reto de integrar la cultura latina con el mercado americano.  Y a pesar de la distancia, el Ecuador la conquista de nuevo, donde inicia sus conocimientos de Community Manager, Redes Sociales y en calidad de directora creativa en Lumapel. </p>
        </div>
      </div>
    </div>
  </div>
<!--
  <div class="staff-wrap">
    <div class="row">
      <div class="staff-info">
        <div class ="col-md-4">
          <div class="item"><%= image_tag 'Perfil.jpg', size: "250", alt: "José Avilés" %></div>

        </div>
        <div class ="col-md-8">
          <h4>José Avilés <span></span></h4>
          <p>Graduado en la especialidad de Electrónica en el Instituto Suárez de Guayaquil, inquieto buscador de conocimiento, vinculado con el mundo gráfico desde su infancia. </p>

          <p>Nació en Guayaquil en 1995, el tercero de 4 hermanos, desde los 4 años se relacionó con mundo de la producción gráfica por sus padres. Aprendió en la imprenta familiar los trucos y secretos necesarios para optimizar la producción y realizar trabajos de calidad.</p>

          <p>Trabajó como prensista hasta que, en abril de 2015, llego a Quito para manejar la maquinaria productiva de Lumapel.
          </p> 
        </div>
      </div>
    </div>
  </div>
-->
</div>
<br><br><br>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contacto") %>


<div class="container">
  <div class="row">
      <div id="map-outer" class="col-md-12">
          <div id="address" class="col-md-4">
            <address>
              <strong>Lumapel</strong><br>
              Los Alelies OE4-48 y Gualaquiza.<br>
              Quito - Ecuador<br>
              <abbr title="Teléfono">Telf:</abbr> 02-229-3948<br>
              <abbr title="Celular">Cel:</abbr> 09-8813-7340
            </address>
            
            <address>
              <a href="mailto:lumapel@hotmail.com">lumapel@hotmail.com</a>
            </address>
          </div>
        <div id="map-container" class="col-md-8">
          <script type="text/javascript">
              handler = Gmaps.build('Google');
              handler.buildMap({ 
                provider: {
                }, 
                internal: {id: 'map-container'}}, function(){
                markers = handler.addMarkers([
                  {
                    "lat": -0.120948,
                    "lng": -78.491303,
                    "infowindow": "Lumapel"
                  }
                ]);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                handler.getMap().setZoom(17);
              });
          </script>
        </div>
      </div><!-- /map-outer -->
  </div> <!-- /row -->
</div>
<br><br><br>

app/views/static_pages/home.html.erb
<% provide(:title, "Inicio") %>


    <%= render 'layouts/carousel' %>       

    <%= render 'layouts/jumbotron' %>  

  <div class="container">

    <!-- Columnas para contenidos -->
    <div class="row">
      <div class="col-md-4">
        <h2>Servicios</h2>
        <p>Infórmate sobre los servicios que ofrecemos. </p>
        <p><%= link_to "Conocer más »", servicios_path, class: "btn btn-default" %></p>
         <hr>
      </div>
     
      <div class="col-md-4">
        <h2>Equipo</h2>
        <p>Conócenos un poco más.</p>
        <p><%= link_to "Conocer más »", about_path, class: "btn btn-default" %></p>
        
        <hr>
     </div>
     
      <div class="col-md-4">
        <h2>Contáctanos</h2>
        <p>Ponte en contácto con nosotros.</p>
        <p><%= link_to "Conocer más »", contact_path, class: "btn btn-default" %></p>
        <hr>
      </div>
    </div>
  </div>
  <br><br><br>
  
 

app/views/static_pages/servicios.html.erb
<% provide(:title, "Servicios") %>

<div class="container">
	<h1>Servicios Lumapel<br>
		<!--
		<small>(Los precios incluyen el servicio puerta a puerta)</small>
-->
		</h1>

	<div class="panel-group" id="accordion">
		<div class="panel panel-default">
			<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
			<div class="panel-heading">
				<h4 class="panel-title">
					
					Diseño Gráfico
					<i class="indicator glyphicon glyphicon-minus pull-right" style="color:#BDBDBD"></i>
				</h4></a>
			</div>
			<div id="collapseOne" class="panel-collapse collapse in">
				<div class="panel-body">
					Creamos y desarrollamos su producto, tomando en cuenta los aspectos funcionales, estéticos y simbólicos para transmitir sus ideas eficazmente.
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
			<div class="panel-heading">
				<h4 class="panel-title">
					Producción Gráfica
					<i class="indicator glyphicon glyphicon-plus pull-right" style="color:#BDBDBD"></i>
				</h4></a>
			</div>
			<div id="collapseTwo" class="panel-collapse collapse">
				<div class="panel-body">
					Producimos sus requerimientos tomando en cuenta los siguientes aspectos:<br>
					<strong>Calidad</strong> Nuestros productos son elaborados con los más altos estandares de calidad.<br>
					<strong>Precio</strong> Buscamos la mejor opción de acuerdo a su presupuesto, para esto ofrecemos distintos tipos de formatos, materiales y terminados.<br>
					<strong>Tiempo</strong> Entregamos su trabajo en el tiempo justo. <br>
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
			<div class="panel-heading">
				<h4 class="panel-title">
					DIseño Web
					<i class="indicator glyphicon glyphicon-plus pull-right" style="color:#BDBDBD"></i>
				</h4></a>
			</div>
			<div id="collapseThree" class="panel-collapse collapse">
				<div class="panel-body">
					Tu página Web es la primera impresión que tus clientes se llevarán de tu empresa, es lo que muestras al mundo. <br>
					Diseñamos tu sitio Web de acuerdo a tus necesidades, para que sea visto desde cualquier dispositivo, sea un teléfono inteligente, tablet, o PC de escritorio, tu sitio siempre se verá bien. 
				</div>
			</div>
		</div>
<!--
		<div class="panel panel-default">
			<a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
				<div class="panel-heading">
					<h4 class="panel-title">
						Plastificado (desde $ 0,000055 USD el centímetro)
						<i class="indicator glyphicon glyphicon-plus pull-right" style="color:#BDBDBD"></i>
					</h4>
				</a>
			</div>
			<div id="collapseFour" class="panel-collapse collapse">
				<div class="panel-body">
					El plastificado es un proceso en el que se añade una capa de plástico, puede ser mate o brillante, sobre el papel para protejerlo y resaltar la impresión. Se puede poner en superficies impresas en offset o en láser. 
				</div>
			</div>
		</div>

		<div class="panel panel-default">
			<a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
				<div class="panel-heading">
					<h4 class="panel-title">
						Filtro UV (desde $ 0,000011 USD el centímetro)
						<i class="indicator glyphicon glyphicon-plus pull-right" style="color:#BDBDBD"></i>
					</h4>
				</a>
			</div>
			<div id="collapseFive" class="panel-collapse collapse">
				<div class="panel-body">
					El filtro Ultra Violeta es un barniz que realza la impresión, es parecido al plastificado, con la diferencia que el plastificado es una capa adicional y el filtro UV es un barniz que se absorbe. 
				</div>
			</div>
		</div>
-->

	</div>
</div>
<br><br><br>

<script type="text/javascript">
	function toggleList(e) {
			$(e.target)
					.prev('.panel-heading')
					.find("i.indicator")
					.toggleClass('glyphicon-minus glyphicon-plus');
	}
	$('#accordion').on('hidden.bs.collapse', toggleList);
	$('#accordion').on('shown.bs.collapse', toggleList);
</script>